# Generated by Django 3.0.8 on 2020-07-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='avaDef.jpg', upload_to='news_images', verbose_name='Фото к статье'),
        ),
    ]
