# Generated by Django 3.0.8 on 2020-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(default='bg_news.jpg', upload_to='news_images', verbose_name='Фото к статье'),
        ),
    ]
